language: node_js
node_js:
- '5.7'
cache:
  directories:
  - node_modules
after_success: npm run coverage
notifications:
  slack:
    secure: uyZdWfqD30NXiWOU9yd7wJf412vtBJLBNsQE1e1i0f/8gRolqPdq4hC3EiGbDA9O0mFmRzhhGHF2fYyi91CprkcZR6FCX9S3q7ccp0PD8Q91SfxMcsGzJ0ayb4lHoYCWsM/mwdhAH1Q+fUKzjNaoXC1yX1ngdemk0drDd3QuBd+irFXbAVsGn7yhbEkTeJ5foNcvp3AL7zXZX2b+Jx/VvvapLdQwluyOG+N2bV8UwKHnIGRhCTR75J8GQ3q7xkiOe5sV4O2NN9MDrXhg1lHGDkTtd14XW3iXcX3acxne41fHxFg+jTM6b9A0uRXUSTIGShSt3EyFnURyr3SfGLbIw2BmSyZSd//qdbqg4A6J2P5i4SSFBmAlBdROfisLF4qzHt5tg+9aRoIzd/SrZ9SV+p9b/iaAP+IqdwDxZNGBA5GvoCVN1ua6CM4NiOyN+F9W/LV+K6vOZ+Oz7MifGXopKkG/bMmAXII67CHOU2Xll04kpqt6bcQX4b/fykvSViPGH0jbmJ0ay8jWHD86blLYJ7GwwxUyVwgvXpET5V/UtemosGEMumheZ70/379ALKuQqlrxVsuDnF4pYZBs7qLDfV+dP14LMyYDljpuotQCwgmhuRY3yM0maZFdPvKOUHlnCAn4Spm5MApClujhxGLzmcuV9dnkCuXtkDvUI08tAcU=
